name: cache

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  install-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          extra-packages: |
            any::pkgdown
            any::devtools
            local::.
          needs: website

      - name: Install local package and pkgdown
        shell: Rscript {0}
        run: |
          if (!requireNamespace("pkgdown", quietly = TRUE)) install.packages("pkgdown")

      # Cache installed dependencies
      - name: Cache R dependencies
        uses: actions/cache@v4
        with:
          # Cache the R package library after dependencies are installed
          path: ~/.cache/R
          key: ${{ runner.os }}-R-${{ hashFiles('DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-R-
