on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

name: test-cache

permissions: read-all

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Restore R dependencies cache
        uses: actions/cache@v4
        with:
          path: ~/R/x86_64-pc-linux-gnu-library/${{ matrix.r_version }}
          key: ${{ runner.os }}-R-${{ hashFiles('DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-R-

      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - name: Check if pkgdown is installed
        run: |
          if (!requireNamespace("pkgdown", quietly = TRUE)) {
            cat("pkgdown is NOT installed.\n")
          } else {
            cat("pkgdown is installed.\n")
          }
        shell: Rscript {0}

      - name: Check if devtools is installed
        run: |
          if (!requireNamespace("devtools", quietly = TRUE)) {
            cat("devtools is NOT installed.\n")
          } else {
            cat("devtools is installed.\n")
          }
        shell: Rscript {0}
